### ISSUE TITLE
DirectoryScanner is error prone

### ISSUE THREAD

**Issue by aight8** [alex-oleshkevich/zf-annotations#2]
I like to use this module but I have still noticed that the internal DirectoryScanner from zend-code is somehow error prone. It throws sometimes warnings etc. and it's difficult to debug.
Now I have the problem that DirectoryScanner->DirectoryScanner() in Module.php returns an empty array - the getFiles method works and I have dozens of files with classes.
I use 1.2.2 because I can't upgrade since I use the zf2 metapackage.
Have you experienced similar issues? Is there a way to make this component more verbose sometimes to ensure that the underneath components works correctly?

**Comment by alex-oleshkevich** [comment]
do you use PHP 7.0.5? If so, you are affected by PHP bug - see https://github.com/zendframework/zend-code/issues/49
