### ISSUE TITLE
Maybe use better code scanner module

### ISSUE THREAD

**Issue by aight8** [alex-oleshkevich/zf-annotations#3]
https://github.com/Roave/BetterReflection

https://github.com/zendframework/zend-code/issues/93

**Comment by alex-oleshkevich** [comment]
I'm thinking about dropping zend-code and use plain doctrine-annotations instead.

**Comment by aight8** [comment]
What's about the discovery functionality? When I understand it correctly neither BetterReflection nor DoctrineAnnotations can scan folders and files. Did I miss something?

I wondering why this module is not more popular (maybe the people don't know it) because it really changes the way you use ZF in the positive manner.

**Comment by alex-oleshkevich** [comment]
http://php.net/manual/en/class.recursivedirectoryiterator.php can handle it easily.

**Comment by aight8** [comment]
Perfect 👍

**Comment by alex-oleshkevich** [comment]
pls, see ^2.3
