### ISSUE TITLE
version 2.3

### ISSUE THREAD

**Issue by Perfect-Web** [alex-oleshkevich/zf-annotations#4]
Hey, are you sure this version works ? i couldnt make it work, not to mention that on config you use a function that is no longer there `use ZfAnnotation\Service\ClassParserFactory;`

**Comment by alex-oleshkevich** [comment]
I see, I've fixed that issue in 2.3.1.
Anyway, that module does not use these services, because it scans directories before Zend bootstraps the application. 
See https://github.com/alex-oleshkevich/zf-annotations/blob/master/src/ZfAnnotation/Module.php for more details.
