### ISSUE TITLE
extended routes

### ISSUE THREAD

**Issue by Perfect-Web** [alex-oleshkevich/zf-annotations#6]
Hey, i have a problem, for example if i have 2 level routes like
a
b extends a
<==== works

a
b extends a
c extends b
<===== doesnt work, gives the following error `Zend\ServiceManager\Exception\ServiceNotCreatedException: Service with name "Zend\Router\Http\TreeRouteStack" could not be created. Reason: Missing "type" option`

**Comment by alex-oleshkevich** [comment]
Pls list you code here.

**Comment by Perfect-Web** [comment]
not much to list

```
/**
     * @Route(name="backend", route="/dashboard", mayTerminate=true)
     */

/**
     * @Route(extends="backend", name="downloads", route="/downloads", mayTerminate=true)
     */

/**
     * @Route(extends="downloads", name="image", route="/image")
     */
```

**Comment by Perfect-Web** [comment]
@alex-oleshkevich any news about this ?

**Comment by alex-oleshkevich** [comment]
@Perfect-Web, is it a class-level or method-level annotations (more detailed code listing would be great) ? this is important.
also, make sure that you are not in the race condition (eg. scanner reads "downloads" before "backend").

i will investigate that issue.

**Comment by alex-oleshkevich** [comment]
another point,

your image route must extend "backend/downloads" route, not "downloads".
change it to and try again:
```php
@Route(extends="backend/downloads", name="image", route="/image")
```

also check that test unit:
https://github.com/alex-oleshkevich/zf-annotations/blob/master/tests/ZfAnnotationTest/Route/ExtendsAnnotationTest.php#L158

**Comment by Perfect-Web** [comment]
@alex-oleshkevich thanks, that was it, i wasnt aware that i need to specify the full tree path on the extends parameter, maybe it is worth to put that in the readme so ppl know that they need to use the full tree path on extends and not only the extends name
